export default {
    SHIPMENT_DETAILS_REQUEST:"SHIPMENT_DETAILS_REQUEST",
    SHIPMENT_DETAILS_REQUEST_SUCCESS:"SHIPMENT_DETAILS_REQUEST_SUCCESS",
    SHIPMENT_DETAILS_REQUEST_ERROR:"SHIPMENT_DETAILS_REQUEST_ERROR"
}